export const cardIds = [
  "joker_black",
  "joker_red",
  "spades_ace",
  "spades_king",
  "spades_queen",
  "spades_jack",
  "spades_ten",
  "hearts_ace",
  "hearts_king",
  "hearts_queen",
  "hearts_jack",
  "hearts_ten",
  "diamonds_ace",
  "diamonds_king",
  "diamonds_queen",
  "diamonds_jack",
  "diamonds_ten",
  "clubs_ace",
  "clubs_king",
  "clubs_queen",
  "clubs_jack",
  "clubs_ten",
] as const
export type CardId = (typeof cardIds)[number]
