# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2.json

#api:
#  insecure: true
#  dashboard: true

entryPoints:
  web:
    address: ":80"
  webSecure:
    address: ":443"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "traefik_dynamic_conf.yml"
